module.exports = {
  ignoredRouteFiles: ['**/.*'],
  future: {
    unstable_tailwind: true,
  },
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^parse5.*/,
    /^unist.*/,
    /^hast.*/,
    /^bail.*/,
    /^trough.*/,
    /^mdast.*/,
    /^micromark.*/,
    /^decode.*/,
    /^character.*/,
    /^property.*/,
    /^space.*/,
    /^comma.*/,
    /^react-markdown$/,
    /^vfile.*/,
    /^trim-lines.*/,
    /^html-void.*/,
    /^zwitch.*/,
    /^stringify.*/,
    /^ccount.*/,
  ],
}
